jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.3
env:
  global:
  - FRAMEWORK_NAME=_PACKAGE_NAME
before_install:
  - ./Scripts/before_install.sh
script:
  - ./Scripts/script.sh
